language: android

sudo: false

branches:
  only: master

script: gradle :rsv_example:assembleRelease

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - platform-tools
    - tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17